# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: data_inspector.spec

# add or remove files that should be synced
files_to_sync:
    - data_inspector.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: data_inspector
# downstream (Fedora) RPM package name
downstream_package_name: data_inspector

jobs:
  - job: copr_build
    owner: conscript89
    project: data_inspector
    trigger: commit
    targets:
      - fedora-stable
